### ISSUE TITLE
Extra vertical scrollbars in codesandbox example.

### ISSUE THREAD

**Issue by thunderkid** [pupudu/window-table#29]
This is a beautiful library!
I noticed that on the [codesandbox example](https://codesandbox.io/s/window-table-basic-example-o258q) and on the [website ](https://window-table.now.sh/docz-guides-striped-table)there are extra vertical scrollbars - an outer one that seems like an accident, and an inner one (which is initially hidden behind the outer one!) that actually does the scrolling. I've played around with the table size and css to try to make the outer one vanish, but can't get it to go away. Is it possible to make it disappear?

**Comment by pupudu** [comment]
Hi @thunderkid 
Thanks for creating this issue. 
I acknowledge this bug. Can reproduce. I will look into this soon.

**Comment by pupudu** [comment]
This has been fixed in v0.9.0

Thanks again for reporting the issue

**Comment by thunderkid** [comment]
Hi,
Actually this is still a problem under the latest Chrome (77.0.3865.90) on the latest Windows 10. This is how the demo site at `https://window-table.now.sh` appears:
![image](https://user-images.githubusercontent.com/6183356/66853200-8c6f8480-ef33-11e9-9241-0d86be8573a2.png)

**Comment by pupudu** [comment]
@thunderkid Apologies. The website was recently changed from https://window-table.now.sh to https://window-table.netlify.com since configuring the static site in now seemed harder than netlify. 

I didn't take down the now.sh domain since there may be references to that site. I will add a redirect and close the old site. 

I checked the new website on browser stack and it works fine for me. Please comment if you still see the error in https://window-table.netlify.com

**Comment by thunderkid** [comment]
Thanks. I agree that this is now fixed.
